### ISSUE TITLE
PagesController::add,editの処理

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Pages#18]
PageModelのデータの扱いが複雑な気がします。

http://book.cakephp.org/2.0/ja/tutorials-and-examples/blog/part-two.html#id5
みたいな感じでできると思います。
少なくとも、$formPage変数はいらない気がします。

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/Pages/commit/8f736dddca9cdc2999b466134f7ff1a4e85654b6#diff-7163902a122f61718dab497c4a0d3b5e
