### ISSUE TITLE
add_plugin.ctpの場所

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Pages#21]
Frameプラグインに持って行った方が良いと思います。

**Comment by s-nakajima** [comment]
plugin managerプラグインに持って言った方が良いと思っていましたが。。。Frameプラグインの方が良いですか？

**Comment by kteraguchi** [comment]
PluginManagerも思ったのですが、呼び出すアクションがFramesControler::addなので、Framesプラグインが良いかとの判断でした。
あと、使用するのはBoxごとだし、色々絡でる処理です。
PluginManagerがある程度できてきたら、切り分け部分の再検討した方が良いかもです。

**Comment by s-nakajima** [comment]
了解です。

**Comment by s-nakajima** [comment]
対応済み
