### ISSUE TITLE
dropdown_menu.ctpについて

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Pages#22]
NetCommons.common_header.ctpエレメントで使用しています。

NavbarHelperみたいなの作って、汎用性持たせとくと良い気がします。
優先度は低めかな。

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/Pages/blob/8ab6a93426f16c27c812d2ecb3373a3366e9381a/View/Elements/dropdown_menu.ctp

このElementは、ページ設定リンクになったため、削除したのでClose
