### ISSUE TITLE
レイアウト処理の問題

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Pages#24]
センター以外に配置したプラグインで使用するcssやjsが出力されないです。
https://github.com/NetCommons3/Topics/issues/2

レイアウトファイルの<head>タグ内でHtmlHelper::css()を読んだ後に、センター以外のプラグインにreqestActionしているためです。

PageLayoutHelper内でセンター以外の描画処理を行うといけそうな気がします。

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/Pages/commit/aa8062f683e9a03fee35884383aae6816e88013f
